const baseClass = [
  {
    name: 'Elsword',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Felsword.png?alt=media&token=590001bd-3af0-403c-a578-8e2e3b713e32',
    characterId: 0,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Aisha',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Faisha.png?alt=media&token=83ed3a09-1aaf-4c2a-8aab-bfb9f541cf65',
    characterId: 1,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Rena',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Frena.png?alt=media&token=7efb02c0-cb99-4023-ac3f-566cfeda605a',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Raven',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fraven.png?alt=media&token=f5678b62-ce43-4c44-9a22-55b2fbc00ebe',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Eve',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Feve.png?alt=media&token=3cf236ea-b900-4650-a9a7-efd5624dc679',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Chung',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fchung.png?alt=media&token=d5c07628-184b-4523-bf08-fb04f3612f49',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Ara',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fara.png?alt=media&token=11cbfcc6-4f89-4aac-ac21-6ddb7f67b8f7',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Elesis',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Felesis.png?alt=media&token=99c20cbc-d08a-4db1-9607-29f2c3bbe82c',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Add',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fadd.png?alt=media&token=f83ea6aa-317e-4526-8ff7-d06de0c04c0f',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Lu',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Flu.png?alt=media&token=7c309cbe-325e-48a9-9c16-a9d67289c046',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Ciel',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fciel.png?alt=media&token=b54d35db-58c4-4eb2-bcd9-221ea499ef02',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Rose',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Frose.png?alt=media&token=dcad2e1b-f12b-4c47-a67c-4da32edf4a9a',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Ain',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fain.png?alt=media&token=f57ef11f-5c77-49c6-bf20-5ff49345e937',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Laby',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Flaby.png?alt=media&token=57641c05-ef01-407b-9309-d8729347bbc3',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 0,
    pathId: 0,
  },
  {
    name: 'Noah',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fnoah.png?alt=media&token=475bfc88-48a6-49f4-87eb-859e8c290f3f',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 0,
    pathId: 0,
  },
]

export default baseClass
