const firstClass = [
  {
    name: 'Sword Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsword-knight.png?alt=media&token=800e5e6f-7bbd-4b81-8fed-946d05be895a',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Magic Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fmagic-knight.png?alt=media&token=2ba86346-23d0-4a7e-91a2-a1faeb6e3dac',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Sheath Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsheath-knight.png?alt=media&token=8a10fbce-e018-490b-8027-90cd42b881e1',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Root Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Froot-knight.png?alt=media&token=675a9874-725b-4c53-9efb-d04a874e0b9a',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'High Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fhigh-magician.png?alt=media&token=1d92ff19-3f80-496c-b7ff-ce304ed5430d',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Dark Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fdark-magician.png?alt=media&token=8a4ebb8a-ed19-4e96-ae84-5bdbbcb4ee4c',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Battle Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fbattle-magician.png?alt=media&token=3c9810b8-0f88-4e2b-a098-a293577c8994',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Wiz Magician',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fwiz-magician.png?alt=media&token=0d58159a-0a8d-4062-bbab-19fa9c959a26',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'Combat Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fcombat-ranger.png?alt=media&token=a24e9307-7c63-4b14-a605-0a69cfe7f556',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Sniping Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fsniping-ranger.png?alt=media&token=8b4a7875-fdc8-46f8-8acf-bdd413f89283',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Trapping Ranger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Ftrapping-ranger.png?alt=media&token=920b086b-0a02-46e4-87f0-12f75a18299b',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Sword Taker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fsword-taker.png?alt=media&token=739eacbb-d8d5-454b-bdca-b5aae77763c0',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Over Taker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fover-taker.png?alt=media&token=f69fb9d2-434d-4f50-9843-e6d24994b1e7',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Weapon Taker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fweapon-taker.png?alt=media&token=59e403ff-9210-48c5-b6d5-48267cabc225',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Code: Exotic',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-exotic.png?alt=media&token=9bae2fe6-2d37-4e28-be6c-a07e60f37632',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Code: Architecture',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-architecture.png?alt=media&token=e779b5ab-1142-4681-9674-b651de86992f',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Code: Electra',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-electra.png?alt=media&token=95d86e16-90c3-4983-a0a0-0d705d16d672',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Code: Unknown',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-unknown.png?alt=media&token=d6131105-c905-49be-a416-1109e79dacc3',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'Fury Guardian',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Ffury-guardian.png?alt=media&token=4efef97b-1a1e-4514-96fa-71f480705e99',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Shooting Guardian',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fshooting-guardian.png?alt=media&token=b6df83e1-0513-4d99-ad7d-8d0ab9f1d7e5',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Shelling Guardian',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fshelling-guardian.png?alt=media&token=62f8a980-4dbb-4aeb-a5ca-7093af7eb4c8',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Little Hsien',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Flittle-hsien.png?alt=media&token=27cb3311-c66b-441a-b99e-82fd3f2c8566',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Little Devil',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Flittle-devil.png?alt=media&token=58cea98b-066e-4568-9571-3d783e6e3d2b',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Little Specter',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Flittle-specter.png?alt=media&token=27a31597-d3d5-4d6c-9c7e-822bf306c6e9',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Saber Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fsaber-knight.png?alt=media&token=797e033d-1505-49a4-8177-db79f5fe9318',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Pyro Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fpyro-knight.png?alt=media&token=50d1dfc1-24ab-4d3b-94a2-4e7d0015aa26',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Dark Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fdark-knight.png?alt=media&token=06a404fb-ac65-42d2-bc37-32aafd8466bb',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Psyshic Tracer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fpsychic-tracer.png?alt=media&token=e0136ca3-7b9a-42d1-8d53-a8e282ba970f',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Arc Tracer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Farc-tracer.png?alt=media&token=d5401cb8-12b9-4829-b53a-b82ebff94780',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Time Tracer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Ftime-tracer.png?alt=media&token=a53e3bf6-1c88-4d83-a87c-7f996fcce4a7',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Chiliarch',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fchiliarch.png?alt=media&token=974fa3fb-13a4-40e5-b6e5-992cb5c14481',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Noblesse',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fnoblesse.png?alt=media&token=b16e53eb-3e60-464d-b07b-cfdcafae6d4d',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Diabla',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdiabla.png?alt=media&token=ffdd3ada-36e7-4771-9667-e729b298ceec',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Dreadlord',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdreadlord.png?alt=media&token=ba8dbff7-87bf-4483-916e-a3938622dcdd',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Royal Guard',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Froyal-guard.png?alt=media&token=621543f2-0bca-452c-9ced-89a2ee8a6d31',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Demonio',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdemonio.png?alt=media&token=4f5a201e-fc97-416a-89cb-f53728c792ae',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Heavy Barrel',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fheavy-barrel.png?alt=media&token=0d3d569a-bb8f-4daf-a612-329c30428ea6',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Bloodia',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fbloodia.png?alt=media&token=91b60a7c-fc8c-4fbf-9660-d3d0ab070c1b',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Valkyrie',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fvalkyrie.png?alt=media&token=320148bd-b017-454d-bb51-33668a1708ef',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Metal Heart',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fmetal-heart.png?alt=media&token=55f7918c-61cb-4712-97db-f36d36727c28',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 1,
    pathId: 3,
  },
  {
    name: 'Lofty: Executor',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Flofty-executor.png?alt=media&token=1f393f82-42dd-43ed-85c7-cad8e2319398',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Lofty: Anpassen',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Flofty-anpassen.png?alt=media&token=8d6ed7c7-4e68-4a31-b4d3-9787e9b05b9b',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Lofty: Wanderer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Flofty-wanderer.png?alt=media&token=691c48a2-6ad8-46dd-89a0-323d1911e0dc',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Sparky Child',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fsparky-child.png?alt=media&token=28543c8f-d76b-4e7e-87d5-a1d6f01d9019',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Twinkle Child',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Ftwinkle-child.png?alt=media&token=8409cdfd-261d-4016-82fe-fe3100bf7583',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 1,
    pathId: 1,
  }, {
    name: 'Rusty Child',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Frusty-child.png?alt=media&token=48bd851a-768c-4a7c-a871-233f9bcfc745',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 1,
    pathId: 2,
  },
  {
    name: 'Second Revenger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsecond-revenger.png?alt=media&token=98541f5d-6082-49d1-a47f-0a4ea3d34961',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 1,
    pathId: 0,
  },
  {
    name: 'Second Selection',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsecond-selection.png?alt=media&token=cb853e80-7c16-4272-b174-41cd7be436b8',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 1,
    pathId: 1,
  },
  {
    name: 'Second Grief',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsecond-grief.png?alt=media&token=18726336-f0a3-4a1b-ac7e-61d991a94d6b',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 1,
    pathId: 2,
  },
]

export default firstClass
