const secondClass = [
  {
    name: 'Lord Knight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Flord-knight.png?alt=media&token=da9f6b22-4899-4f15-9c04-6028e3bbe912',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Rune Slayer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-slayer.png?alt=media&token=87e4489c-f8e9-490b-be6e-3cb8cf9d7a25',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Infinity Sword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Finfinity-sword.png?alt=media&token=7905c1fd-3f63-4fd9-af42-164cc8399b55',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Sacred Templar',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsacred-templar.png?alt=media&token=c9320eac-4912-42ad-b31f-df96f72ee56e',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 2,
    pathId: 3,
  },
  {
    name: 'Elemental Master',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Felemental-master.png?alt=media&token=3f150e4a-57ad-4e57-abbb-51dfc77bd71f',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Void Princess',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fvoid-princess.png?alt=media&token=d6a75ae9-94a2-4cd1-bcfa-99a172332f7f',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Dimension Witch',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fdimension-witch.png?alt=media&token=3aba92d1-6418-42f6-afba-964a687c1bb5',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Mystic Alchemist',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fmystic-alchemist.png?alt=media&token=3158aed9-49d3-4a90-bb4d-5f9dea77ca4a',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 2,
    pathId: 3,
  },
  {
    name: 'Wind Sneaker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fwind-sneaker.png?alt=media&token=17eb0ebe-2293-4dbb-bf24-ee2abb1b59c4',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Grand Archer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fgrand-archer.png?alt=media&token=28934e81-a65e-420a-be1a-8cdf7e2179f4',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Night Watcher',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fnight-watcher.png?alt=media&token=57f1089f-835a-4707-b493-bb3c4b3565bb',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Blade Master',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fblade-master.png?alt=media&token=7813a963-4a5c-4d92-9a9a-704aa34555dc',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Reckless Fist',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Freckless-fist.png?alt=media&token=0123d1ce-7cc2-4e87-a47c-c2107e059cd2',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Veteran Commander',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fveteran-commander.png?alt=media&token=e33a0696-32a8-41aa-987f-e2697d53ec90',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Code: Nemesis',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-nemesis.png?alt=media&token=ca65c85a-95f1-4970-804c-89be31ed46fa',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Code: Empress',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-empress.png?alt=media&token=b6ea096f-46e8-4d62-8fc1-42bbe8b6c0ec',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Code: Battle Seraph',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-battle-seraph.png?alt=media&token=563c9872-0469-44da-9c04-9e8594a49277',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Code: Failess',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-failess.png?alt=media&token=5c6eef8b-04ee-4a2e-905c-b2c4dbca1d9b',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 2,
    pathId: 3,
  },
  {
    name: 'Iron Paladin',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Firon-paladin.png?alt=media&token=6c01b7c1-ab41-41be-9803-31d97648dab8',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Deadly Chaser',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fdeadly-chaser.png?alt=media&token=1c812261-21f3-41d1-baef-fc136dcc0e80',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Tactical Trooper',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Ftactical-trooper.png?alt=media&token=bf20e022-d3ff-4e46-941d-b18a058780cb',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Sakra Devanam',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fsakra-devanam.png?alt=media&token=ee671f27-74c0-47e5-b00c-c4f29d4e0604',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Yama Raja',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fyama-raja.png?alt=media&token=410e3fde-2aa5-42f6-a80b-d09cba449b19',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Asura',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fasura.png?alt=media&token=ef721814-c767-4784-aad6-0df0981c9383',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Grand Master',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fgrand-master.png?alt=media&token=b9651045-fe20-4044-a19e-5bb97e8f70f0',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Blazing Heart',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fblazing-heart.png?alt=media&token=1fc8b6ad-e4d8-41d9-b34b-f5d364fd8641',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Crimson Avenger',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fcrimson-avenger.png?alt=media&token=3ae987b7-a631-44c0-8c71-a66babf98dd3',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Lunatic Psyker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Flunatic-psyker.png?alt=media&token=53a59b0d-8b9b-4fc1-aaf7-7b46572cbe68',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Mastermind',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fmastermind.png?alt=media&token=87cda009-fdc6-4126-8b86-dfefc92cf6f8',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Diabolic Esper',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fdiabolic-esper.png?alt=media&token=2d5af881-9c43-4420-91d1-feff67ab1e1c',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Storm Trooper',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fstorm-trooper.png?alt=media&token=83d78400-fdd8-49ca-9f85-5427ed9e5b37',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Crimson Rose',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fcrimson-rose.png?alt=media&token=0242b5ba-82a6-4cfa-8217-fb20dacb68f3',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Freyja',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Ffreyja.png?alt=media&token=bf17559b-56e2-4ff9-ac02-5091202109b4',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Optimus',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Foptimus.png?alt=media&token=5b1f9adb-fee0-4c1a-9cde-d86e7bdadbbc',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 2,
    pathId: 3,
  },
  {
    name: 'Arme Thaumaturgy',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Farme-thaumaturgy.png?alt=media&token=c6731175-b991-413c-9a14-b0736c723dd6',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Erbluhen Emotion',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Ferbluhen-emotion.png?alt=media&token=e53f43df-2781-4c88-8e7a-d9a179876511',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Apostasia',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fapostasia.png?alt=media&token=ec294a80-cee7-402d-ac71-0ce3149b56e0',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Rumble Pumn',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Frumble-pumn.png?alt=media&token=b38f9e35-fb82-48f8-ba4d-c9f933284ead',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Shinning Romantica',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fshining-romantica.png?alt=media&token=e90a525d-89a4-445b-9d44-97432b4875e3',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Daydreamer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fdaydreamer.png?alt=media&token=f6f7b203-719f-4f04-995f-f56763519a74',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Silent Shadow',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsilent-shadow.png?alt=media&token=03a14668-6cac-416d-a7de-df02000da072',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 2,
    pathId: 0,
  },
  {
    name: 'Stellar Caster',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fstellar-caster.png?alt=media&token=b90f5ed0-2766-465b-9baa-065653d06178',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Pale Pilgrim',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fpale-pilgrim.png?alt=media&token=5db7d600-db23-4f15-8ab8-ed71bf34959d',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 2,
    pathId: 2,
  },
]

export default secondClass
