const thirdClass = [
  {
    name: 'Knight Emperor',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fknight-emperor.png?alt=media&token=f61d4722-9fad-4365-ad84-e396aa597156',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Rune Master',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-master.png?alt=media&token=15496cf6-ad41-4b12-9c36-5b721967473b',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Immortal',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fimmortal.png?alt=media&token=4b0c3fbf-30e9-4c24-bab0-cc5078a63d4c',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Genesis',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fgenesis.png?alt=media&token=9f7b734a-d5ad-453b-8389-4dc69aa569e3',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 4,
    pathId: 3,
  },
  {
    name: 'Aether Sage',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Faether-sage.png?alt=media&token=a2b72dfa-de33-43ad-890b-3b331e317ab3',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Oz Sorcerer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Foz-sorcerer.png?alt=media&token=9be7ff50-5c77-4dc4-b59b-c613ee41c013',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Metamorphy',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fmetamorphy.png?alt=media&token=b86f5d7b-df42-4da5-b384-61af4b9ec3d7',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Lord Azoth',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Flord-azoth.png?alt=media&token=24a0b9e1-d760-4bfa-8698-863f6ae6280b',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 4,
    pathId: 3,
  },
  {
    name: 'Anemos',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fanemos.png?alt=media&token=3a8a1108-f72a-48be-ac5c-3a24c4aebad7',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Daybreaker',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fdaybreaker.png?alt=media&token=350e8ee1-2927-48c8-bea3-a47e3dd56947',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Twilight',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Ftwilight.png?alt=media&token=7ac37e2a-66cd-44cd-9cf3-77f20d682a98',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Furious Blade',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Ffurious-blade.png?alt=media&token=47d5d10b-30bc-4494-90ab-1cb9ad04f843',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Rage Hearts',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Frage-hearts.png?alt=media&token=0a52a622-604d-4ac0-b0b4-032b774448d9',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Nova Imperator',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fnova-imperator.png?alt=media&token=b6fea89a-8d10-4ba8-ab4e-e54e27aba9b9',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Code: Ultimate',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-ultimate.png?alt=media&token=9bf36eaa-b81e-4f65-99e4-c86d5a5ca7f2',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Code: Essencia',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-essencia.png?alt=media&token=3f7ab4d9-7447-4d94-b566-c04c18213e18',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Code: Sariel',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-sariel.png?alt=media&token=3864fd45-a631-42e5-b3eb-ef935181a352',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Code: Antithese',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-antithese.png?alt=media&token=2bccddd7-5816-49f7-937f-2a06edc15e0e',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 4,
    pathId: 3,
  },
  {
    name: 'Comet Crusader',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fcomet-crusader.png?alt=media&token=75a3ce19-2919-49b7-9e74-438bc79bd8d3',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Fatal Phantom',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Ffatal-phantom.png?alt=media&token=2f3c8e50-e94d-4c47-ad01-fa1b22486cdf',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Centurion',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fcenturion.png?alt=media&token=36e34528-ef84-4c23-97fb-41b59013af66',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Apsara',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fapsara.png?alt=media&token=dbf45663-58e1-46e2-82c5-174a6c684d28',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Devi',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fdevi.png?alt=media&token=cbd4303b-79d9-4599-90f8-6e054e5e6ebe',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Shakti',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fshakti.png?alt=media&token=c2be15cd-d3ac-4a39-89fd-8ce7fcc75e21',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Empire Sword',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fempire-sword.png?alt=media&token=ddbc6091-6f99-4f3c-ac67-b65dcc9a6bea',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Flame Lord',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fflame-lord.png?alt=media&token=f42a57f7-963f-496e-bc8a-a1791f37fbb9',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Bloody Queen',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fbloody-queen.png?alt=media&token=059c29c8-a274-4743-8d7c-6ca0c41c856d',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Doom Bringer',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fdoom-bringer.png?alt=media&token=f5746258-1688-431b-b752-57a02799b282',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Dominator',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fdominator.png?alt=media&token=f01e7323-6a34-4059-a626-5054b18f7733',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Mad Paradox',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fmad-paradox.png?alt=media&token=543c68c4-eb12-4c63-847c-1ae1878c7820',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Catastrophe(Timoria)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Ftimoria.png?alt=media&token=08623ebd-9699-4e46-8246-e19b69470f93',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Innocent(Ishtar)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fishtar.png?alt=media&token=e51f6856-5ea5-4b05-ad71-3fb04f330b3d',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Diangelion(Iblis)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fiblis.png?alt=media&token=91d70179-960e-4e14-b693-bced1d73b589',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Catastrophe(Abysser)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fabysser.png?alt=media&token=10e37c5d-5811-47a0-8c29-64e86234e185',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Innocent(Chevalier)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fchevalier.png?alt=media&token=108a0225-55fc-426f-b6fb-5c59e2750504',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Diangelion(Anular)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fanular.png?alt=media&token=c79d7b0c-790d-4ef2-982f-b11ee4e1d5d9',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Tempest Burster',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Ftempest-burster.png?alt=media&token=bf1c3fcf-186e-4a05-a5b0-1ab8c05c0536',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Black Massacre',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fblack-massacre.png?alt=media&token=aa1095a3-ceb4-41bf-abcb-6e8069cc3109',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Minerva',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fminerva.png?alt=media&token=1a549ec6-83e8-475f-b5af-45d9126aaa7e',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Prime Operator',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fprime-operator.png?alt=media&token=97072598-cd2f-4ebd-9e8a-8771ac1449c7',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 4,
    pathId: 3,
  },
  {
    name: 'Ritcher',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fritcher.png?alt=media&token=1c88ae8f-dfec-4e1a-bf21-1daa9657d0ea',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Bluhen',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fbluhen.png?alt=media&token=d35d7c47-aa56-4554-ae3d-7eaf8a7c4df7',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 2,
    pathId: 1,
  },
  {
    name: 'Herrscher',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fherrscher.png?alt=media&token=0224de2a-9106-42a0-b6a9-089357218d57',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 2,
    pathId: 2,
  },
  {
    name: 'Eternity Winter',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Feternity-winter.png?alt=media&token=d2a163ab-1dab-4781-bf7a-b6e1a49ce4e2',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Radiant Soul',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fradiant-soul.png?alt=media&token=b825672b-0d09-4e42-bcf3-2fbe31fc2c21',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Nisha Labyrinth',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fnisha-labyrinth.png?alt=media&token=f7356de4-2794-4116-b125-0004d1c375fc',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 4,
    pathId: 2,
  },
  {
    name: 'Liberator',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fliberator.png?alt=media&token=f0cb8be8-1ecd-4143-ad31-b44f2fee1514',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 4,
    pathId: 0,
  },
  {
    name: 'Celestia',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fcelestia.png?alt=media&token=503a6c33-a4df-4343-b529-6c099e899202',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 4,
    pathId: 1,
  },
  {
    name: 'Nyx Pieta',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fnyx-pieta.png?alt=media&token=8566acd9-529d-48ee-a1ce-29fdde2c33fa',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 4,
    pathId: 2,
  },
]

export default thirdClass
