const transcendentClass = [
  {
    name: 'Lord Knight (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Flord-knight-trans.png?alt=media&token=625697f8-1bf5-4656-bb26-5bdb18c65bc3',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Rune Slayer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Frune-slayer-trans.png?alt=media&token=694be52f-c73f-4097-9d53-3187de5f06ee',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Infinity Sword (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Finfinity-sword-trans.png?alt=media&token=ad4b1baf-b75f-480f-900f-957f8530e2be',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Sacred Templar (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felsword%2Fsacred-templar-trans.png?alt=media&token=b7e00465-4375-4576-9b3d-f7950521d932',
    bgColor: 'bg-elsword',
    textColor: 'text-elsword dark:text-elsword-dark',
    hoverBgColor: 'hover:bg-elsword',
    characterId: 0,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Elemental Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Felemental-master-trans.png?alt=media&token=23821e85-1466-4e60-bd10-360090bc30f5',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Void Princess (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fvoid-princess-trans.png?alt=media&token=a12b5a80-6208-4a7a-853a-f4645e969b53',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Dimension Witch (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fdimension-witch-trans.png?alt=media&token=492ed58c-a3ae-4a11-bc22-7636ca410f9f',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Mystic Alchemist (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Faisha%2Fmystic-alchemist-transcendent.png?alt=media&token=d42bc725-c734-4b84-8019-e523ea2d4a33',
    bgColor: 'bg-aisha',
    textColor: 'text-aisha dark:text-aisha-dark',
    hoverBgColor: 'hover:bg-aisha',
    characterId: 1,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Wind Sneaker (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fwind-sneaker-trans.png?alt=media&token=9fb2979e-e9c1-4e14-bb97-4fc21db0e77d',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Grand Archer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fgrand-archer-trans.png?alt=media&token=e369279f-df3d-4b73-bdcf-8457381afbc7',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Night Watcher (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frena%2Fnight-watcher-trans.png?alt=media&token=0ef559ec-7aec-4491-85f7-79329808cf58',
    bgColor: 'bg-rena',
    textColor: 'text-rena',
    hoverBgColor: 'hover:bg-rena',
    characterId: 2,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Blade Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fblade-master-trans.png?alt=media&token=4b60441b-ca1e-4625-a6e6-88e71667f524',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Reckless Fist (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Freckless-fist-trans.png?alt=media&token=135d780a-bf6d-438f-a4e4-93e4c70d8057',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Veteran Commander (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fraven%2Fveteran-commander-trans.png?alt=media&token=fa68b45d-40d2-41de-bd34-cdbd31402826',
    bgColor: 'bg-raven',
    textColor: 'text-raven dark:text-raven-dark',
    hoverBgColor: 'hover:bg-raven',
    characterId: 3,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Code: Nemesis (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-nemesis-trans.png?alt=media&token=c24ad81a-0220-47e9-aeb0-2bdaf474d823',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Code: Empress (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-empress-trans.png?alt=media&token=1b30105e-b32e-4826-a603-f5026b1a650d',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Code: Battle Seraph (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-battle-seraph-trans.png?alt=media&token=9b383bc4-b9fb-4075-b09a-48bb3788c086',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Code: Failess (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Feve%2Fcode-failess-trans.png?alt=media&token=67f5ecc3-a62b-44c8-8848-713399835f37',
    bgColor: 'bg-eve',
    textColor: 'text-eve',
    hoverBgColor: 'hover:bg-eve',
    characterId: 4,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Iron Paladin (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Firon-paladin-trans.png?alt=media&token=2515b937-217d-41c4-9260-d6678b9897ba',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Deadly Chaser (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Fdeadly-chaser-trans.png?alt=media&token=e371d2d9-a360-4b8a-bbb3-60ca09758981',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Tactical Trooper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fchung%2Ftactical-trooper-trans.png?alt=media&token=b447a730-6021-441a-8b5f-190cd5ec7feb',
    bgColor: 'bg-chung',
    textColor: 'text-chung',
    hoverBgColor: 'hover:bg-chung',
    characterId: 5,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Sakra Devanam (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fsakra-devanam-trans.png?alt=media&token=4b4a4874-faac-4ed0-9230-1c44876e88c7',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Yama Raja (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fyama-raja-trans.png?alt=media&token=00737216-9362-43c3-84e4-62fc934e0b04',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Asura (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fara%2Fasura-trans.png?alt=media&token=11530201-af16-4206-9829-06e3d5c34b97',
    bgColor: 'bg-ara',
    textColor: 'text-ara',
    hoverBgColor: 'hover:bg-ara',
    characterId: 6,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Grand Master (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fgrand-master-trans.png?alt=media&token=0b396e9e-e754-4041-98c5-30e6e846bab5',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Blazing Heart (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fblazing-heart-trans.png?alt=media&token=843d210a-f151-4e93-b3e1-c9f6144f2162',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Crimson Avenger (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Felesis%2Fcrimson-avenger-trans.png?alt=media&token=825a1238-c5ee-4da7-bb9c-ce8951748b06',
    bgColor: 'bg-elesis',
    textColor: 'text-elesis dark:text-elesis-dark',
    hoverBgColor: 'hover:bg-elesis',
    characterId: 7,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Lunatic Psyker (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Flunatic-psyker-trans.png?alt=media&token=aaac52ea-df6b-4bac-a21a-ddcf825cd9a1',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Mastermind (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fmastermind-trans.png?alt=media&token=d7a0b5e3-b9e5-46f5-9a85-f2873ad15458',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Diabolic Esper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fadd%2Fdiabolic-esper-trans.png?alt=media&token=f733e96f-e05b-4dd7-b0d7-ff9fa4c70a8b',
    bgColor: 'bg-add',
    textColor: 'text-add',
    hoverBgColor: 'hover:bg-add',
    characterId: 8,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Chiliarch (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fchiliarch-trans.png?alt=media&token=2470298a-f226-4b8f-8cb1-aa40f7934c24',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Noblesse (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fnoblesse-trans.png?alt=media&token=9d87dacb-461c-4180-8ed4-c7babb1a9b10',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Diabla (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdiabla-trans.png?alt=media&token=eb60bd9c-ee2d-496d-9183-81d39e33e57c',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 9,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Dreadlord (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdreadlord-trans.png?alt=media&token=e2f47120-3c68-48b0-bd9f-8503daf0a245',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Royal Guard (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Froyal-guard-trans.png?alt=media&token=2c78f5a4-d18c-4209-8fcd-0f5eb9220456',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Demonio (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flu-ciel%2Fdemonio-trans.png?alt=media&token=9f544aeb-4704-48c7-86f2-dc7f416b85a4',
    bgColor: 'bg-luciel',
    textColor: 'text-luciel dark:text-luciel-dark',
    hoverBgColor: 'hover:bg-luciel',
    characterId: 10,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Storm Trooper (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fstorm-trooper-trans.png?alt=media&token=0ab82dc1-f68f-4713-8ec9-e5d52ee1008c',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Crimson Rose (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Fcrimson-rose-trans.png?alt=media&token=4bf3928c-5d74-4777-9416-e83d4f6e1f19',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Freyja (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Ffreyja-trans.png?alt=media&token=3f6c1401-de20-4c3c-bda7-497aa0be39f1',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Optimus (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Frose%2Foptimus-trans.png?alt=media&token=52d3ad29-6186-4dd7-aacd-7a74d94e4629',
    bgColor: 'bg-rose',
    textColor: 'dark:text-rose text-gray-600',
    hoverTextColor: 'hover:text-gray-600 dark:hover:text-gray-600',
    hoverBgColor: 'hover:bg-rose',
    characterId: 11,
    classId: 3,
    pathId: 3,
  },
  {
    name: 'Arme Thaumaturgy (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Farme-thaumaturgy-trans.png?alt=media&token=a6d27335-b9fc-4921-8b09-90bfc6b8311f',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Erbluhen Emotion (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Ferbluhen-emotion-trans.png?alt=media&token=2d41a0a7-8286-4896-801f-abefac8f0c95',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Apostasia (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fain%2Fapostasia-trans.png?alt=media&token=11a3957b-c7dc-477c-b2ef-9173d14c7f79',
    bgColor: 'bg-ain',
    textColor: 'text-ain',
    hoverBgColor: 'hover:bg-ain',
    characterId: 12,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Rumble Pumn (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Frumble-pumn-trans.png?alt=media&token=7c4b3e72-df85-4d9f-87e6-d212969d92d0',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Shinning Romantica (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fshining-romantica-trans.png?alt=media&token=e609ca23-9d96-426e-a3e9-74421f5de56a',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Daydreamer (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Flaby%2Fdaydreamer-trans.png?alt=media&token=0271eefe-18d1-4a3a-9bdc-63ef3a2c1829',
    bgColor: 'bg-laby',
    textColor: 'text-laby',
    hoverBgColor: 'hover:bg-laby',
    characterId: 13,
    classId: 3,
    pathId: 2,
  },
  {
    name: 'Silent Shadow (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fsilent-shadow-trans.png?alt=media&token=8017d73a-16fe-40ab-bd4c-ed17a18a4b4f',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 0,
  },
  {
    name: 'Stellar Caster (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fstellar-caster-trans.png?alt=media&token=ee7638a0-1a20-46e5-992d-314cfe719dd1',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 1,
  },
  {
    name: 'Pale Pilgrim (T)',
    img: 'https://firebasestorage.googleapis.com/v0/b/elfun-web-app.appspot.com/o/images%2Favatar%2Fnoah%2Fpale-pilgrim-trans.png?alt=media&token=0db84e9d-2169-40fd-a43e-6b402d7b7fba',
    bgColor: 'bg-noah',
    textColor: 'text-noah',
    hoverBgColor: 'hover:bg-noah',
    characterId: 14,
    classId: 3,
    pathId: 2,
  },
]

export default transcendentClass
