import Head from 'next/head'
import Layout from 'components/layouts/default-layout'
import { ReactElement } from 'react'
import Button from 'components/common/button'

const Home = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta content='Generated by create next app' name='description' />
      <link href='/favicon.ico' rel='icon' />
    </Head>
    <main>
      <Button
        label='Button'
      />
    </main>
  </div>
)

Home.getLayout = (page:ReactElement) => (
  <Layout>
    {page}
  </Layout>
)

export default Home
