import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = function () {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <main className='bg-pink-600'>
        asasd
      </main>

    </div>
  )
}

export default Home
